services:
  postgres:
    image: postgres:17
    container_name: postgres-decimal-test
    environment:
      POSTGRES_DB: decimal_test
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d decimal_test"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: